### ISSUE TITLE
cURL SSL certificate problem

### ISSUE THREAD

**Issue by payalord** [sensiolabs/SensioBuzzBundle#22]
I'm using symfony2, and i got this error:

```
SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

symfony\vendor\kriswallsmith\buzz\lib\Buzz\Client\Curl.php at line 29

I didn't installed SensioBuzzBundle nor Buzz Client too. It comes as part of symfony2 framework i guess.
I tried to find solution, and i found this http://stackoverflow.com/questions/10620024/symfony2-send-a-http-request

But, those options not working for me:
```
# cURL client for Buzz
buzz.client.curl:
  class:  Buzz\Client\Curl
  public: false
  calls:
    - [setVerifyPeer, [false]]
```
Plus while i'm testing my website on local server, it is fine with `[setVerifyPeer, [false]]`, but on production server. That is not fine. What if i will want to switch it on? I will get the error again?

Maybe will be better to add ability to configure cURL from *.yml file? To deal with this problem?
